name: WebAdmin
main: de.tutorialwork.webadmin.main.Main
author: Tutorialwork
version: 1.1

commands:
  web:
    description: Create an webaccount or change the password
  webadmin:
  status:
    description: List infos about operators and whitelist